require 'nokogiri'
require_relative 'eagle/settings'
require_relative 'eagle/grid'
require_relative 'eagle/layer'
require_relative 'eagle/part'
require_relative 'eagle/instance'
require_relative 'eagle/net'
require_relative 'eagle/sheet'
require_relative 'eagle/drawing'
require_relative 'eagle/technology'
require_relative 'eagle/device'
require_relative 'eagle/deviceset'
require_relative 'eagle/package'
require_relative 'eagle/library'

