require 'nokogiri'
require_relative 'eagle/settings'
require_relative 'eagle/grid'
require_relative 'eagle/layer'
require_relative 'eagle/part'
require_relative 'eagle/instance'
require_relative 'eagle/sheet'
require_relative 'eagle/drawing'
